#!/bin/bash

for file in *.html; do
    if [ -f "$file" ]; then
        parent_file="../$file"
        
        if [ ! -f "$parent_file" ]; then
            cp "$file" "../$file"
            echo "Copied new file: $file to parent directory"
        else
            if [ "$file" -nt "$parent_file" ]; then
                cp "$file" "../$file"
                echo "Updated: $file in parent directory"
            fi
        fi
    fi
done